[1mdiff --git a/src/station1.html b/src/station1.html[m
[1mindex bd69ccd..39fc30b 100644[m
[1m--- a/src/station1.html[m
[1m+++ b/src/station1.html[m
[36m@@ -1,11 +1,27 @@[m
 <!DOCTYPE html>[m
 <html lang="ja">[m
[32m+[m
 <head>[m
[31m-<meta charset="UTF-8">[m
[31m-<meta http-equiv="X-UA-Compatible" content="IE=edge">[m
[31m-<meta name="viewport" content="width=device-width, initial-scale=1.0">[m
[31m-<title>Station 1</title>[m
[32m+[m[32m  <meta charset="UTF-8">[m
[32m+[m[32m  <meta http-equiv="X-UA-Compatible" content="IE=edge">[m
[32m+[m[32m  <meta name="viewport" content="width=device-width, initial-scale=1.0">[m
[32m+[m[32m  <title>Station 1</title>[m
 </head>[m
[32m+[m
 <body>[m
[32m+[m[32m  <div class="main">[m
[32m+[m[32m  <div class="image">[m
[32m+[m[32m    <img src="src/assets/image/railway-thumbnail.png" alt="">[m
[32m+[m[32m  </div>[m
[32m+[m[32m  <div class="text">[m
[32m+[m[32m    <p><span>TechTrain</span>の使い方</p>[m
[32m+[m[32m    <p><span>TechBowl</span></p>[m
[32m+[m[32m  </div>[m
[32m+[m[32m  <div class="sub">[m
[32m+[m[32m    <p>Suguru Ohki</p>[m
[32m+[m[32m    <p>6,722回視聴・2021/04/22</p>[m
[32m+[m[32m  </div>[m
[32m+[m[32m</div>[m
 </body>[m
[31m-</html>[m
[32m+[m
[32m+[m[32m</html>[m
\ No newline at end of file[m
